# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.13
    resource_class: xlarge
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - add_ssh_keys:
          fingerprints:
            - "8a:0e:bb:a1:17:8e:b3:4e:5c:44:65:40:62:af:73:5a"
      - run:
          name: Install dependencies
          command: |
            sudo apt update && sudo apt-get install python3-pip parallel g++-6 gcc-6 bzr build-essential -y
            python3 --version
            pip3 --version
            pip3 install setuptools
            go get github.com/rakyll/statik
            free -m
            df -lh
      - run:
          name: Env set up
          command: |
            export GO111MODULE=on
            export GOPRIVATE=github.com/coinexchain/*
            export GOROOT=$(go env GOROOT)
            export CXX="g++-6" CC="gcc-6"
            export PATH=$PATH:$HOME/gopath/bin
      - run:
          name: Project set up
          command: |
            go mod tidy
            make statik-swagger
            make build-linux
      - run:
          name: Docker proceed
          command: |
            docker build . --tag=coinexchain/cetdtest
            bash scripts/functional_test.sh 4 0





